"""rename department

Revision ID: 447ca8ca60fa
Revises: dd7fe39682c0
Create Date: 2024-06-27 15:34:26.446145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447ca8ca60fa'
down_revision = 'dd7fe39682c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
